In [1]:
import numpy as np

In [7]:
def normalize_swizzle_rotation(wxyz):
    return np.roll(np.array(wxyz / np.linalg.norm(wxyz)), -1)

# e1 e2 e3 e4
def pack_smallest_3_rotation(q):
    abs_q = np.abs(q)
    index = np.argmax(abs_q, axis=1)
    q_rolled = np.roll(q, -index-1, axis=1)
    signs = np.sign(q_rolled[:, 3])
    three = q_rolled[:, :3] * signs[:, np.newaxis]
    three = (three * np.sqrt(2)) * 0.5 + 0.5
    index = index / 3.0
    return np.column_stack((three, index)) 

In [8]:
rot = np.array([[2.71330, -0.23072, 0.18155, -0.03790]])
rot = normalize_swizzle_rotation(rot)
rot = pack_smallest_3_rotation(rot)
rot

array([[0.44022728, 0.54703423, 0.49018123, 1.        ]])

In [21]:
import numpy as np

# Create two arrays with the same number of rows
minimo = np.array([[1, 2, 1], [3, 4, 3], [5, 6, 5]])
maximo = np.array([[7, 8,1], [9, 10,4], [11, 12,4]])

# Stack the columns of the arrays horizontally
output = np.array([np.ravel([mi,ma],order='F') for mi,ma in zip(minimo,maximo)])

print(output)

[[ 1  7  2  8  1  1]
 [ 3  9  4 10  3  4]
 [ 5 11  6 12  5  4]]


In [22]:
first = [1,2,3,4]
second = [5,6,7,8]

In [24]:
data = np.concatenate((first, second))
data

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
import os
import cv2

data_path = "data/dynerf/sear_steak/"

# Create a VideoCapture object and read from input file
cams = []

for i in [2]:
    name = data_path + "cam" + str(i).zfill(2) 
    cam = cv2.VideoCapture(name + ".mp4")

    try:
        os.mkdir(name)
        outpath = os.path.join(name, "images/")
        os.mkdir(outpath)
    except:
        continue

    if (cam.isOpened()== False):
        print("Error opening video stream or file")
    
    # Read until video is completed
    j = 0
    while True:
        ret, frame = cam.read()

        if ret == True:
            frame = cv2.resize(frame, (1352, 1014), interpolation=cv2.INTER_AREA)
            cv2.imwrite(outpath + "/" + str(j).zfill(4) + ".png", frame)
            j += 1
        else:
            break
    
    print(f"Done with {name}")
